export const SITE = {
  name: "Agency Orchestrator",
  short: "ao",
  repo: "https://github.com/jnMetaCode/agency-orchestrator",
  npm: "https://www.npmjs.com/package/agency-orchestrator",
  rolesRepo: "https://github.com/jnMetaCode/agency-agents-zh",
  issues: "https://github.com/jnMetaCode/agency-orchestrator/issues",
  changelog: "https://github.com/jnMetaCode/agency-orchestrator/blob/main/CHANGELOG.md",
  license: "https://github.com/jnMetaCode/agency-orchestrator/blob/main/LICENSE",
  evalFindings: "https://github.com/jnMetaCode/agency-orchestrator/blob/main/EVAL_FINDINGS.md",
  install: "npm i -g agency-orchestrator",
  sponsorContact: "https://github.com/jnMetaCode/agency-orchestrator/issues/new?title=Sponsorship",
  providersKeyed: ["DeepSeek", "Claude", "OpenAI", "Gemini", "Ollama", "Moonshot", "硅基流动", "OpenRouter"],
  providersKeyfree: ["claude-code CLI", "gemini-cli", "openclaw-cli", "Ollama 本地", "LM Studio", "免费聚合", "演示模式"],
};
